version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    reviewers:
      - "ocean90"

  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 10
    reviewers:
      - "ocean90"
