// See @wordpress/prettier-config.
const prettierConfig = {
	useTabs: true,
	tabWidth: 4,
	printWidth: 100, // Default 80.
	singleQuote: true,
	trailingComma: 'es5',
	bracketSpacing: true,
	parenSpacing: true,
	bracketSameLine: false,
	semi: true,
	arrowParens: 'always',
};

module.exports = {
	root: true,
	env: {
		browser: true,
		es6: true,
	},
	extends: [ 'plugin:@wordpress/eslint-plugin/recommended' ],
	rules: {
		'prettier/prettier': [ 'error', prettierConfig ],
	},
	settings: {
		'import/core-modules': [
			'react',
			'react-dom',
			'lodash',
			'lodash-es',
			'jquery',
			'moment',
			'@wordpress/a11y',
			'@wordpress/annotations',
			'@wordpress/api-fetch',
			'@wordpress/autop',
			'@wordpress/blob',
			'@wordpress/block-directory',
			'@wordpress/block-editor',
			'@wordpress/block-library',
			'@wordpress/block-serialization-default-parser',
			'@wordpress/blocks',
			'@wordpress/components',
			'@wordpress/compose',
			'@wordpress/core-data',
			'@wordpress/data',
			'@wordpress/data-controls',
			'@wordpress/date',
			'@wordpress/deprecated',
			'@wordpress/dom',
			'@wordpress/dom-ready',
			'@wordpress/edit-post',
			'@wordpress/editor',
			'@wordpress/element',
			'@wordpress/escape-html',
			'@wordpress/format-library',
			'@wordpress/hooks',
			'@wordpress/html-entities',
			'@wordpress/i18n',
			'@wordpress/is-shallow-equal',
			'@wordpress/keyboard-shortcuts',
			'@wordpress/keycodes',
			'@wordpress/list-reusable-blocks',
			'@wordpress/media-utils',
			'@wordpress/notices',
			'@wordpress/nux',
			'@wordpress/plugins',
			'@wordpress/primitives',
			'@wordpress/priority-queue',
			'@wordpress/redux-routine',
			'@wordpress/reusable-blocks',
			'@wordpress/rich-text',
			'@wordpress/server-side-render',
			'@wordpress/shortcode',
			'@wordpress/token-list',
			'@wordpress/url',
			'@wordpress/viewport',
			'@wordpress/warning',
			'@wordpress/wordcount',
		],
	},
};
