const wordpress = require( '@wordpress/eslint-plugin' );

// See @wordpress/prettier-config.
const prettierConfig = {
	useTabs: true,
	tabWidth: 4,
	printWidth: 100, // Default 80.
	singleQuote: true,
	trailingComma: 'es5',
	bracketSpacing: true,
	parenSpacing: true,
	bracketSameLine: false,
	semi: true,
	arrowParens: 'always',
};

// Modules the WordPress build externalizes to `wp-*` script handles, so they
// resolve at runtime and must not be flagged by `import/no-unresolved` /
// `import/no-extraneous-dependencies`. The @wordpress entries are every package
// with `wpScript: true` minus the `BUNDLED_PACKAGES` of
// @wordpress/dependency-extraction-webpack-plugin (e.g. icons, interface,
// dataviews, undo-manager), plus the special interactivity externals.
const coreModules = [
	'react',
	'react-dom',
	'lodash',
	'lodash-es',
	'jquery',
	'moment',
	'@wordpress/a11y',
	'@wordpress/annotations',
	'@wordpress/api-fetch',
	'@wordpress/autop',
	'@wordpress/base-styles',
	'@wordpress/blob',
	'@wordpress/block-directory',
	'@wordpress/block-editor',
	'@wordpress/block-library',
	'@wordpress/block-serialization-default-parser',
	'@wordpress/block-serialization-spec-parser',
	'@wordpress/blocks',
	'@wordpress/commands',
	'@wordpress/components',
	'@wordpress/compose',
	'@wordpress/core-commands',
	'@wordpress/core-data',
	'@wordpress/customize-widgets',
	'@wordpress/data',
	'@wordpress/data-controls',
	'@wordpress/date',
	'@wordpress/deprecated',
	'@wordpress/dom',
	'@wordpress/dom-ready',
	'@wordpress/edit-post',
	'@wordpress/edit-site',
	'@wordpress/edit-widgets',
	'@wordpress/editor',
	'@wordpress/element',
	'@wordpress/escape-html',
	'@wordpress/format-library',
	'@wordpress/hooks',
	'@wordpress/html-entities',
	'@wordpress/i18n',
	'@wordpress/interactivity',
	'@wordpress/interactivity-router',
	'@wordpress/is-shallow-equal',
	'@wordpress/keyboard-shortcuts',
	'@wordpress/keycodes',
	'@wordpress/list-reusable-blocks',
	'@wordpress/media-utils',
	'@wordpress/notices',
	'@wordpress/nux',
	'@wordpress/patterns',
	'@wordpress/plugins',
	'@wordpress/preferences',
	'@wordpress/preferences-persistence',
	'@wordpress/primitives',
	'@wordpress/priority-queue',
	'@wordpress/private-apis',
	'@wordpress/react-i18n',
	'@wordpress/redux-routine',
	'@wordpress/reusable-blocks',
	'@wordpress/rich-text',
	'@wordpress/router',
	'@wordpress/server-side-render',
	'@wordpress/shortcode',
	'@wordpress/style-engine',
	'@wordpress/sync',
	'@wordpress/theme',
	'@wordpress/token-list',
	'@wordpress/upload-media',
	'@wordpress/url',
	'@wordpress/viewport',
	'@wordpress/warning',
	'@wordpress/widgets',
	'@wordpress/wordcount',
];

module.exports = [
	...wordpress.configs.recommended,
	{
		settings: {
			'import/core-modules': coreModules,
		},
		rules: {
			'prettier/prettier': [ 'error', prettierConfig ],
		},
	},
];
